export class ComptrollerPaymentModel {
  constructor(public Row: number,
              public FiscalYear: number,
              public ContractTitle: string,
              public ContractorName: string,
              public ContractCost: number,
              public ContractNum: string,
              public Deputy: string,
              public Department: string,
              public PaymentType: string,
              public LetterDate: string,
              public ApprovedDate: string,
              public VoucherNum: number,
              public VoucherDescription: string,
              public CostReasourceId: number,
              public PaymentType2: string,
              public GrossAmount: number,
              public Deposits: number,
              public PayableInsurance: number,
              public Tax: number,
              public PrepaidDepreciation: number,
              public MaterialPrepaidDepreciation: number,
              public Fine: number,
              public TotalDeductions: number,
              public VAT: number,
              public EmployerInsurance: number,
              public TreasuryBillsProfit: number,
              public NetAmount: number,
              public AllocatedCredit: number,
              public BankAmount: number,) {
  }
}
